[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "python-dotenv>=1.0.0",
    "scikit-learn>=1.6.1",
    "spotipy>=2.25.1",
    "streamlit>=1.43.1",
    "twilio>=9.4.6",
]
